FROM oven/bun:1

WORKDIR /user/app


ARG DATABASE_URL

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN bun install

RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build


EXPOSE 3001

CMD [ "bun", "run", "start:backend"]