FROM oven/bun:1

WORKDIR /user/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/backend ./apps/backend

RUN bun install

RUN bun run db:generate

EXPOSE 3001

CMD [ "bun", "run", "start:backend"]