name: deploying the backend

on:
  push:
    branches: [ main ]


jobs: 
  build:
    runs-on: ubuntu-latest
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Login to docker
      uses: docker/login-action@v2
      with: 
        username: 